# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48eef10215c5306ae77b1a00190ec95464a7463710e1423a374bcb3c9248e9792277d7bd79403006233ea4e25acf3cc41fd38b97a0eea09e50e0e4242487fd7e

test:
  secret_key_base: b5db001c009d7a607f563f9b37e6121097fa256dd95e1aa5c28489212f0c9f455e7919521b6dde306530ed46fa1348794d2420dd9e876f1433526b1fb0fab89e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
